<?
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["*"]="D";
$PERM["/"]["8"]="R";
$PERM["/"]["*"]="R";
$PERM["news"]["8"]="W";
$PERM["news"]["5"]="W";
$PERM["ads"]["8"]="W";
$PERM["about_service"]["8"]="W";
$PERM["account_seller"]["2"]="D";
$PERM["account_seller"]["8"]="W";
$PERM["account_seller"]["7"]="R";
$PERM["account_seller"]["*"]="D";
$PERM["account_buyer"]["8"]="W";
$PERM["account_buyer"]["6"]="R";
$PERM["account_buyer"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>